-- AEMS Pilot Student Load
-- Source: AVF July 2026 attendance data
-- Pilot CCs: MACHERLA ANITHA and SARITHA
-- Pilot centres: 26AG08, 26AG09, 26AG10, 26KP06, 26KP07, 26KP08
-- Minimum fields loaded: student_code, student_name, gender, center_id
-- No historical attendance is loaded by this script.

BEGIN;

-- Validate that all six pilot centres exist.
DO $$
DECLARE
    missing_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO missing_count FROM (VALUES ('26AG08'), ('26AG09'), ('26AG10'), ('26KP06'), ('26KP07'), ('26KP08')) AS p(center_code)
    WHERE NOT EXISTS (
        SELECT 1 FROM public.tuition_center tc
        WHERE tc.center_code = p.center_code
    );
    IF missing_count > 0 THEN
        RAISE EXCEPTION 'One or more pilot centres are missing from tuition_center';
    END IF;
END $$;

-- Load/update only the six pilot centres.
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'GELUKARA NIDHISHA', 'Girl', TRUE, '26AG0801' FROM public.tuition_center tc WHERE tc.center_code = '26AG08' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0801');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'PRIYANSHU SINGH', 'Girl', TRUE, '26AG0802' FROM public.tuition_center tc WHERE tc.center_code = '26AG08' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0802');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'K ANKITHA YADAV', 'Girl', TRUE, '26AG0803' FROM public.tuition_center tc WHERE tc.center_code = '26AG08' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0803');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'SUPRIYA SINGH', 'Girl', TRUE, '26AG0804' FROM public.tuition_center tc WHERE tc.center_code = '26AG08' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0804');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'CHINTHA MOKSHIT', 'Boy', TRUE, '26AG0805' FROM public.tuition_center tc WHERE tc.center_code = '26AG08' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0805');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'POTAKARI MANANYA', 'Girl', TRUE, '26AG0806' FROM public.tuition_center tc WHERE tc.center_code = '26AG08' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0806');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'SOUDURU KOMALI', 'Girl', TRUE, '26AG0807' FROM public.tuition_center tc WHERE tc.center_code = '26AG08' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0807');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'GADDAPATI ABHILASH', 'Boy', TRUE, '26AG0808' FROM public.tuition_center tc WHERE tc.center_code = '26AG08' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0808');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'SHAIK SANIA', 'Girl', TRUE, '26AG0809' FROM public.tuition_center tc WHERE tc.center_code = '26AG08' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0809');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'PADVGUMMALU YADAIAH', 'Boy', TRUE, '26AG0810' FROM public.tuition_center tc WHERE tc.center_code = '26AG08' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0810');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'RADAPAKA SRI HALYA', 'Girl', TRUE, '26AG0811' FROM public.tuition_center tc WHERE tc.center_code = '26AG08' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0811');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'GUNJAKAR AAROHI', 'Girl', TRUE, '26AG0812' FROM public.tuition_center tc WHERE tc.center_code = '26AG08' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0812');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'BODDU MAHA', 'Girl', TRUE, '26AG0813' FROM public.tuition_center tc WHERE tc.center_code = '26AG08' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0813');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'BATTA RAKSHITHA', 'Girl', TRUE, '26AG0814' FROM public.tuition_center tc WHERE tc.center_code = '26AG08' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0814');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'BATTA VINITH VARSHAN', 'Boy', TRUE, '26AG0815' FROM public.tuition_center tc WHERE tc.center_code = '26AG08' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0815');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'SHAIK SUHANA', 'Girl', TRUE, '26AG0816' FROM public.tuition_center tc WHERE tc.center_code = '26AG08' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0816');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'BONTHA HARSHITHA', 'Girl', TRUE, '26AG0817' FROM public.tuition_center tc WHERE tc.center_code = '26AG08' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0817');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'BONTHA AMULYA', 'Girl', TRUE, '26AG0818' FROM public.tuition_center tc WHERE tc.center_code = '26AG08' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0818');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'KASANI THARUN', 'Boy', TRUE, '26AG0819' FROM public.tuition_center tc WHERE tc.center_code = '26AG08' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0819');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'GELULARA CHASIKA', 'Girl', TRUE, '26AG0820' FROM public.tuition_center tc WHERE tc.center_code = '26AG08' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0820');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'K.DHANUSHA', 'Boy', TRUE, '26AG0821' FROM public.tuition_center tc WHERE tc.center_code = '26AG08' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0821');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'V.PRANEETH', 'Boy', TRUE, '26AG0822' FROM public.tuition_center tc WHERE tc.center_code = '26AG08' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0822');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'MD.ARMAN', 'Boy', TRUE, '26AG0823' FROM public.tuition_center tc WHERE tc.center_code = '26AG08' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0823');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'V.MUKESH', 'Boy', TRUE, '26AG0824' FROM public.tuition_center tc WHERE tc.center_code = '26AG08' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0824');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'PILLI RAMYA SRI', 'Girl', TRUE, '26AG0825' FROM public.tuition_center tc WHERE tc.center_code = '26AG08' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0825');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'BALURUGU SREE ARADHMA', 'Girl', TRUE, '26AG0901' FROM public.tuition_center tc WHERE tc.center_code = '26AG09' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0901');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'VEMULA KARTHIK', 'Boy', TRUE, '26AG0902' FROM public.tuition_center tc WHERE tc.center_code = '26AG09' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0902');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'BANOTH LAXMI', 'Girl', TRUE, '26AG0903' FROM public.tuition_center tc WHERE tc.center_code = '26AG09' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0903');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'ORSU SANKEERTHANA', 'Girl', TRUE, '26AG0904' FROM public.tuition_center tc WHERE tc.center_code = '26AG09' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0904');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'ORSU THANUJA', 'Girl', TRUE, '26AG0905' FROM public.tuition_center tc WHERE tc.center_code = '26AG09' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0905');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'ORSU RISHIKA', 'Girl', TRUE, '26AG0906' FROM public.tuition_center tc WHERE tc.center_code = '26AG09' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0906');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'BALURUGU DINESH', 'Boy', TRUE, '26AG0907' FROM public.tuition_center tc WHERE tc.center_code = '26AG09' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0907');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'MAKKALA THANUJA', 'Girl', TRUE, '26AG0908' FROM public.tuition_center tc WHERE tc.center_code = '26AG09' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0908');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'MAKKALA SRIHIK TEJA', 'Boy', TRUE, '26AG0909' FROM public.tuition_center tc WHERE tc.center_code = '26AG09' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0909');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'ORAGANTI DHAYVAKRUPA', 'Girl', TRUE, '26AG0910' FROM public.tuition_center tc WHERE tc.center_code = '26AG09' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0910');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'BONTHA AADHYA SREE', 'Girl', TRUE, '26AG0911' FROM public.tuition_center tc WHERE tc.center_code = '26AG09' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0911');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'BONTHA ADVIKTEJ', 'Boy', TRUE, '26AG0912' FROM public.tuition_center tc WHERE tc.center_code = '26AG09' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0912');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'SHIVARATHRI GANESH', 'Boy', TRUE, '26AG0913' FROM public.tuition_center tc WHERE tc.center_code = '26AG09' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0913');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'SHIVARATHRI THARUN TEJA', 'Boy', TRUE, '26AG0914' FROM public.tuition_center tc WHERE tc.center_code = '26AG09' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0914');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'BOLLEDULA KEERTHI SRI', 'Girl', TRUE, '26AG0915' FROM public.tuition_center tc WHERE tc.center_code = '26AG09' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0915');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'GOLLENA BHARADWAJ', 'Boy', TRUE, '26AG0916' FROM public.tuition_center tc WHERE tc.center_code = '26AG09' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0916');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'BONTHA BRUVAN', 'Boy', TRUE, '26AG0917' FROM public.tuition_center tc WHERE tc.center_code = '26AG09' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG0917');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'ALAKUNTA VARSHITHA', 'Girl', TRUE, '26AG1001' FROM public.tuition_center tc WHERE tc.center_code = '26AG10' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG1001');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'CHARLAPALLY HARSHINI', 'Girl', TRUE, '26AG1002' FROM public.tuition_center tc WHERE tc.center_code = '26AG10' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG1002');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'DAYYALA THANMAYU', 'Girl', TRUE, '26AG1003' FROM public.tuition_center tc WHERE tc.center_code = '26AG10' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG1003');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'DAYYALA YAKSHITH', 'Boy', TRUE, '26AG1004' FROM public.tuition_center tc WHERE tc.center_code = '26AG10' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG1004');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'SHIVARATHRI STELLA', 'Girl', TRUE, '26AG1005' FROM public.tuition_center tc WHERE tc.center_code = '26AG10' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG1005');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'ORSU AKHILA', 'Girl', TRUE, '26AG1006' FROM public.tuition_center tc WHERE tc.center_code = '26AG10' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG1006');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'VALLAPU KULPA', 'Girl', TRUE, '26AG1007' FROM public.tuition_center tc WHERE tc.center_code = '26AG10' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG1007');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'ALAKUNTLA SANMUKTH', 'Boy', TRUE, '26AG1008' FROM public.tuition_center tc WHERE tc.center_code = '26AG10' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG1008');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'PALLAPU HANI', 'Girl', TRUE, '26AG1009' FROM public.tuition_center tc WHERE tc.center_code = '26AG10' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG1009');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'CHARLAPALLY VARSHINI', 'Girl', TRUE, '26AG1010' FROM public.tuition_center tc WHERE tc.center_code = '26AG10' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG1010');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'CHARLAPALLU MOKSHITH', 'Boy', TRUE, '26AG1011' FROM public.tuition_center tc WHERE tc.center_code = '26AG10' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG1011');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'SHIVARATHRI AMMULU', 'Girl', TRUE, '26AG1012' FROM public.tuition_center tc WHERE tc.center_code = '26AG10' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG1012');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'SHERLA DEEKSHITHA', 'Girl', TRUE, '26AG1013' FROM public.tuition_center tc WHERE tc.center_code = '26AG10' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG1013');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'SHIVARATHRI AJAY', 'Boy', TRUE, '26AG1014' FROM public.tuition_center tc WHERE tc.center_code = '26AG10' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG1014');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'VADLAKONDA RESHWANTH', 'Boy', TRUE, '26AG1015' FROM public.tuition_center tc WHERE tc.center_code = '26AG10' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG1015');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'BITKUR ROHINI', 'Girl', TRUE, '26AG1016' FROM public.tuition_center tc WHERE tc.center_code = '26AG10' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG1016');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'SADEVADA BAVESH', 'Boy', TRUE, '26AG1017' FROM public.tuition_center tc WHERE tc.center_code = '26AG10' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG1017');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'PONNA SAI PRANEETH', 'Boy', TRUE, '26AG1018' FROM public.tuition_center tc WHERE tc.center_code = '26AG10' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG1018');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'BABARAV INGALE SHREYASH', 'Boy', TRUE, '26AG1019' FROM public.tuition_center tc WHERE tc.center_code = '26AG10' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG1019');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'BITKURI VEDANTH', 'Boy', TRUE, '26AG1020' FROM public.tuition_center tc WHERE tc.center_code = '26AG10' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG1020');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'CHIRRA VIGENESWAR', 'Boy', TRUE, '26AG1021' FROM public.tuition_center tc WHERE tc.center_code = '26AG10' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG1021');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'CHIRRA SMANSI', 'Girl', TRUE, '26AG1022' FROM public.tuition_center tc WHERE tc.center_code = '26AG10' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG1022');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'PONNA DURGA SREE', 'Girl', TRUE, '26AG1023' FROM public.tuition_center tc WHERE tc.center_code = '26AG10' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG1023');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'BITKURI GOUTHAM BHAVANI', 'Girl', TRUE, '26AG1024' FROM public.tuition_center tc WHERE tc.center_code = '26AG10' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26AG1024');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'PUPPAL AKHIL', 'Boy', TRUE, '26KP0601' FROM public.tuition_center tc WHERE tc.center_code = '26KP06' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0601');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'K GEETHIKA', 'Girl', TRUE, '26KP0602' FROM public.tuition_center tc WHERE tc.center_code = '26KP06' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0602');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'VADDERA MEGHANA', 'Girl', TRUE, '26KP0603' FROM public.tuition_center tc WHERE tc.center_code = '26KP06' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0603');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'KOMMU VIVEK MADHU', 'Boy', TRUE, '26KP0604' FROM public.tuition_center tc WHERE tc.center_code = '26KP06' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0604');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'VADDERA SANDEEP', 'Boy', TRUE, '26KP0605' FROM public.tuition_center tc WHERE tc.center_code = '26KP06' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0605');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'GNANADEEPIKA DULGAJ', 'Girl', TRUE, '26KP0606' FROM public.tuition_center tc WHERE tc.center_code = '26KP06' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0606');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'MD MUDASIR ABDUL MUKHID', 'Boy', TRUE, '26KP0607' FROM public.tuition_center tc WHERE tc.center_code = '26KP06' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0607');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'LETLA ESHWAR', 'Boy', TRUE, '26KP0608' FROM public.tuition_center tc WHERE tc.center_code = '26KP06' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0608');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'DOMATI SAI CHANDU', 'Boy', TRUE, '26KP0609' FROM public.tuition_center tc WHERE tc.center_code = '26KP06' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0609');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'SHARANYA SRI', 'Girl', TRUE, '26KP0610' FROM public.tuition_center tc WHERE tc.center_code = '26KP06' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0610');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'DUDEKULA ASIYA FATHIMA', 'Girl', TRUE, '26KP0611' FROM public.tuition_center tc WHERE tc.center_code = '26KP06' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0611');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'VEDDERA SANDEEP', 'Boy', TRUE, '26KP0612' FROM public.tuition_center tc WHERE tc.center_code = '26KP06' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0612');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'VEVAN REDDY', 'Boy', TRUE, '26KP0613' FROM public.tuition_center tc WHERE tc.center_code = '26KP06' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0613');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'M SAMATHA', 'Girl', TRUE, '26KP0614' FROM public.tuition_center tc WHERE tc.center_code = '26KP06' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0614');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'G JAINITH', 'Boy', TRUE, '26KP0615' FROM public.tuition_center tc WHERE tc.center_code = '26KP06' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0615');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'SANJAY', 'Boy', TRUE, '26KP0616' FROM public.tuition_center tc WHERE tc.center_code = '26KP06' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0616');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'PULICHERLA MOHAN SAI ARUN TEJ REDDY', 'Boy', TRUE, '26KP0617' FROM public.tuition_center tc WHERE tc.center_code = '26KP06' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0617');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'J VIJENDRA VARMA', 'Boy', TRUE, '26KP0618' FROM public.tuition_center tc WHERE tc.center_code = '26KP06' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0618');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'LAW KUMAR', 'Boy', TRUE, '26KP0619' FROM public.tuition_center tc WHERE tc.center_code = '26KP06' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0619');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'N PUSHPA', 'Girl', TRUE, '26KP0620' FROM public.tuition_center tc WHERE tc.center_code = '26KP06' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0620');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'K SNEHA', 'Girl', TRUE, '26KP0621' FROM public.tuition_center tc WHERE tc.center_code = '26KP06' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0621');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'K AARVI', 'Girl', TRUE, '26KP0622' FROM public.tuition_center tc WHERE tc.center_code = '26KP06' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0622');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'PULICHERIA SAI DURGATHRISANK REDDY', 'Boy', TRUE, '26KP0623' FROM public.tuition_center tc WHERE tc.center_code = '26KP06' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0623');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'SHANIGARAM MANVITH', 'Boy', TRUE, '26KP0624' FROM public.tuition_center tc WHERE tc.center_code = '26KP06' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0624');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'PATHAKOTI HEMANTH', 'Boy', TRUE, '26KP0701' FROM public.tuition_center tc WHERE tc.center_code = '26KP07' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0701');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'PATHAKOTI SAI ESHWAR', 'Boy', TRUE, '26KP0702' FROM public.tuition_center tc WHERE tc.center_code = '26KP07' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0702');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'KUNCHALA MOHIT KUMAR', 'Boy', TRUE, '26KP0703' FROM public.tuition_center tc WHERE tc.center_code = '26KP07' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0703');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'DOMATI DEEKSHITHA', 'Girl', TRUE, '26KP0704' FROM public.tuition_center tc WHERE tc.center_code = '26KP07' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0704');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'CHIDUGU BHANU PRASAD GOUD', 'Boy', TRUE, '26KP0705' FROM public.tuition_center tc WHERE tc.center_code = '26KP07' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0705');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'CHIDUGU ASHWITH GOUD', 'Boy', TRUE, '26KP0706' FROM public.tuition_center tc WHERE tc.center_code = '26KP07' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0706');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'MYATHARI MANISH', 'Boy', TRUE, '26KP0707' FROM public.tuition_center tc WHERE tc.center_code = '26KP07' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0707');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'E SHIVA PRASANNA', 'Girl', TRUE, '26KP0708' FROM public.tuition_center tc WHERE tc.center_code = '26KP07' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0708');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'CHAKALI  AKHILA', 'Girl', TRUE, '26KP0709' FROM public.tuition_center tc WHERE tc.center_code = '26KP07' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0709');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'B AMIT ACHARI', 'Boy', TRUE, '26KP0710' FROM public.tuition_center tc WHERE tc.center_code = '26KP07' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0710');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'S AKSHAYA', 'Girl', TRUE, '26KP0711' FROM public.tuition_center tc WHERE tc.center_code = '26KP07' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0711');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'KRUTHIKA', 'Girl', TRUE, '26KP0712' FROM public.tuition_center tc WHERE tc.center_code = '26KP07' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0712');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'VADDERN KIRANMAYE', 'Girl', TRUE, '26KP0713' FROM public.tuition_center tc WHERE tc.center_code = '26KP07' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0713');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'LINGALA DIVYA SREE', 'Girl', TRUE, '26KP0714' FROM public.tuition_center tc WHERE tc.center_code = '26KP07' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0714');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'B PRAVEEN ACHARI', 'Boy', TRUE, '26KP0715' FROM public.tuition_center tc WHERE tc.center_code = '26KP07' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0715');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'NARASIMHA', 'Boy', TRUE, '26KP0716' FROM public.tuition_center tc WHERE tc.center_code = '26KP07' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0716');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'A SATISH', 'Boy', TRUE, '26KP0717' FROM public.tuition_center tc WHERE tc.center_code = '26KP07' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0717');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'GUDEPU SHIVA', 'Boy', TRUE, '26KP0718' FROM public.tuition_center tc WHERE tc.center_code = '26KP07' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0718');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'BODA DEVANUSH', 'Boy', TRUE, '26KP0801' FROM public.tuition_center tc WHERE tc.center_code = '26KP08' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0801');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'ASIS KUMAR DIGAJ', 'Boy', TRUE, '26KP0802' FROM public.tuition_center tc WHERE tc.center_code = '26KP08' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0802');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'VADDE ABHINASH', 'Boy', TRUE, '26KP0803' FROM public.tuition_center tc WHERE tc.center_code = '26KP08' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0803');
INSERT INTO public.student_master (center_id, student_name, gender, active_flag, student_code) SELECT tc.center_id, 'RAJIYA KUMARI', 'Girl', TRUE, '26KP0804' FROM public.tuition_center tc WHERE tc.center_code = '26KP08' AND NOT EXISTS (SELECT 1 FROM public.student_master sm WHERE sm.student_code = '26KP0804');

-- Verification
SELECT tc.center_code, COUNT(sm.student_id) AS student_count
FROM public.tuition_center tc
LEFT JOIN public.student_master sm
  ON sm.center_id = tc.center_id
 AND sm.active_flag = TRUE
WHERE tc.center_code IN ('26AG08','26AG09','26AG10','26KP06','26KP07','26KP08')
GROUP BY tc.center_code
ORDER BY tc.center_code;

COMMIT;